name: CI

on:
  push:
    branches:
      - main # or the name of your default branch
  pull_request:
    branches:
      - main # or the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Run Tests
      run: npm test