name: Publish Package to NPM

on:
  push:
    branches:
      - master # or your default branch name

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # or your desired Node version
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@v10.0.1

    - name: Build
      run: |
        npm run build

    - name: Publish
      run: cd dist && npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}